version: '3.6'

services:
  dockersql.application.webapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "9091:80"
  
  mysql.database:
    environment:
      - MYSQL_ROOT_PASSWORD=123Aa321      
    ports:
      - "3306:3306"

