version: '3.6'

networks: 
  dockersql-network:
    driver: bridge

services:
  dockersql.application.webapi:
    image: dockersql.application.webapi
    build:
      context: .
      dockerfile: Example.WebApi/Dockerfile
    networks:
      - dockersql-network
    depends_on:
      - mysql.database

  mysql.database:
    image: mysql
    networks:
      - dockersql-network